"""empty message

Revision ID: 058d86907952
Revises: eda65f1b65dd
Create Date: 2020-05-01 15:21:47.319178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058d86907952'
down_revision = 'eda65f1b65dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'create_time')
    # ### end Alembic commands ###
