"""empty message

Revision ID: 77c8091d0929
Revises: 058d86907952
Create Date: 2020-05-01 17:16:29.837501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c8091d0929'
down_revision = '058d86907952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('support', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'support')
    # ### end Alembic commands ###
