import os


USERNAME = 'root'
PASSWORD = '111111'
HOSTNAME = '127.0.0.1'
PORT = 'root'
DATABASE = 'mydb'
SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_MODIFICATIONS = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_ENCODING = 'utf-8'
DEBUG = True
SERVERPORT = 9999
SECRET_KEY = os.urandom(24)
